// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct CubeCoordinates {

	int x;
    int y;
    int z;
    
};

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<CubeCoordinates> bTiles;
CubeCoordinates target;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

}
